### ISSUE TITLE
pMeshEnt usage

### ISSUE THREAD

**Issue by RuixiongHu** [SCOREC/fep#1] opened 2019-01-31 19:16 UTC
Hi, I would like to ask about the usage of pMeshEnt.

While creating mesh using pumi_mesh_createElem(), since its return type is pMeshEnt, can I create vector<pMeshEnt> and use push back to save the created entity's handle in a vector. So later on if I could use "vector<pMeshEng>[i]" as a pMeshEng type to do any interrogation, or even serves as a way of looping over whole mesh.

Actually I could save handles into the vector, but error occurs while calling them as an element in vector, the error is as follow:
 
2019-01-31 13:07:54.940 (WARN ) [0xfff81e79160] 2328607:ibm.runjob.client.Job: terminated by signal 11
2019-01-31 13:07:54.941 (WARN ) [0xfff81e79160] 2328607:ibm.runjob.client.Job: abnormal termination by signal 11 from rank 0

I see these error couple of times so would also like to know what does this indicate?

Really appreciate any help.
Thanks

**Comment by cwsmith** [comment] 2019-01-31 19:28
Try using an iterator after the mesh is created instead of reusing the input vector of vertices.

`signal 11` is a segmentation fault.

On the BGQ you can check the meaning of signals by running the command `man 7 signal`.

**Comment by cwsmith** [comment] 2019-02-07 00:42
I'm going to close this issue assuming that the problem is resolved.  Please reopen it if needed.

**Closed as completed by cwsmith** 2019-02-07 00:42 UTC
Labels: question
